# Step 1:- importing the libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib as plt

## to import the data from the given data source using NSEpy package
import nsepy as ns
from datetime import date, datetime

# Step 2:- Importing the data from the given data source

In [2]:
## A) Importing the data for NSE  stocks (INFY,TCS) between 2014-2016. Data level - Daily.
infy ,tcs= (ns.get_history(symbol = s, start= date(2015,1,1),
                          end= date(2016,12,31))for s in ["INFY","TCS"])

In [3]:
infy # to view the data frame
# it has 495 rows * 14 columns

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154
2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371
2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370
2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332
2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270
2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920
2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004
2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702
2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295
2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390
2015-01-15,INFY,EQ,2128.65,2135.20,2152.80,2112.25,2130.00,2134.25,2137.46,2085613,4.457911e+14,48882,1410992,0.6765
2015-01-16,INFY,EQ,2134.25,2148.00,2160.00,2112.00,2115.00,2118.30,2125.77,1672740,3.555858e+14,63848,1254004,0.7497
2015-01-19,INFY,EQ,2118.30,2120.00,2132.35,2094.60,2105.00,2102.50,2104.55,1021936,2.150713e+14,62963,673948,0.6595
2015-01-20,INFY,EQ,2102.50,2107.00,2133.00,2101.45,2119.20,2124.20,2118.16,1701126,3.603258e+14,66871,1284137,0.7549
2015-01-21,INFY,EQ,2124.20,2131.50,2175.95,2118.00,2172.00,2169.90,2148.41,2123727,4.562628e+14,82679,1394125,0.6565
2015-01-22,INFY,EQ,2169.90,2174.80,2203.00,2161.30,2194.95,2196.45,2193.10,2489599,5.459951e+14,82961,1879561,0.7550
2015-01-23,INFY,EQ,2196.45,2200.00,2225.00,2165.10,2211.90,2215.05,2194.58,2371582,5.204624e+14,78929,1622130,0.6840
2015-01-27,INFY,EQ,2215.05,2221.00,2221.00,2130.10,2137.55,2136.50,2146.45,3434992,7.373022e+14,117167,2765575,0.8051
2015-01-28,INFY,EQ,2136.50,2150.00,2154.80,2130.30,2144.45,2144.55,2144.31,3283589,7.041041e+14,99134,2313485,0.7046
2015-01-29,INFY,EQ,2144.55,2145.00,2149.90,2127.60,2147.80,2145.50,2141.67,3842356,8.229076e+14,79209,2797911,0.7282
2015-01-30,INFY,EQ,2145.50,2161.50,2162.55,2126.95,2141.85,2141.90,2144.44,2708436,5.808066e+14,99180,2093132,0.7728
2015-02-02,INFY,EQ,2141.90,2141.50,2152.00,2126.05,2137.00,2136.85,2142.80,2175635,4.661958e+14,47871,1641719,0.7546
2015-02-03,INFY,EQ,2136.85,2136.85,2139.95,2102.00,2124.00,2120.90,2117.92,1316489,2.788217e+14,64490,821456,0.6240
2015-02-04,INFY,EQ,2120.90,2139.90,2150.00,2126.40,2143.80,2142.85,2142.92,1290004,2.764378e+14,49317,889211,0.6893
2015-02-05,INFY,EQ,2142.85,2150.80,2220.00,2148.00,2186.00,2193.80,2189.61,2968984,6.500912e+14,112707,2025011,0.6821
2015-02-06,INFY,EQ,2193.80,2205.00,2247.80,2188.50,2228.00,2230.50,2229.51,1863432,4.154534e+14,79072,1073921,0.5763
2015-02-09,INFY,EQ,2230.50,2200.00,2254.00,2200.00,2245.00,2248.90,2238.75,1634217,3.658597e+14,96994,1074815,0.6577
2015-02-10,INFY,EQ,2248.90,2243.00,2298.00,2241.00,2268.00,2278.30,2270.89,2129230,4.835242e+14,84805,1385146,0.6505
2015-02-11,INFY,EQ,2278.30,2280.50,2293.20,2256.25,2287.80,2284.85,2279.82,1449243,3.304009e+14,58510,962023,0.6638
2015-02-12,INFY,EQ,2284.85,2283.00,2321.95,2273.00,2309.90,2311.20,2301.63,1571884,3.617897e+14,66827,995751,0.6335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-21,INFY,EQ,920.00,926.90,926.90,906.95,914.00,911.10,918.76,3970284,3.647743e+14,129057,3044568,0.7668
2016-11-22,INFY,EQ,911.10,916.90,928.65,911.65,914.85,914.20,918.14,2741563,2.517130e+14,106048,2006559,0.7319
2016-11-23,INFY,EQ,914.20,922.10,922.90,912.45,921.00,920.25,918.81,4125893,3.790923e+14,130883,3540359,0.8581
2016-11-24,INFY,EQ,920.25,928.20,939.90,923.30,930.00,930.30,931.71,8390322,7.817314e+14,131479,7064694,0.8420
2016-11-25,INFY,EQ,930.30,930.45,985.00,930.45,974.70,977.50,971.84,6315690,6.137815e+14,206134,3658597,0.5793
2016-11-28,INFY,EQ,977.50,979.30,983.45,970.60,978.05,979.75,978.12,3682856,3.602268e+14,114279,2635667,0.7157
2016-11-29,INFY,EQ,979.75,978.80,984.70,967.10,973.45,972.60,976.81,3062753,2.991718e+14,84322,2280029,0.7444
2016-11-30,INFY,EQ,972.60,973.00,977.00,961.05,974.05,975.55,973.42,4250459,4.137474e+14,99676,2430712,0.5719
2016-12-01,INFY,EQ,975.55,976.00,983.55,967.00,974.95,975.60,974.84,2305795,2.247778e+14,68019,1555051,0.6744
2016-12-02,INFY,EQ,975.60,964.80,969.60,961.10,963.00,964.50,966.01,2226614,2.150941e+14,130557,1576117,0.7079
2016-12-05,INFY,EQ,964.50,965.90,968.60,958.00,961.00,961.65,961.83,1829788,1.759944e+14,57931,1226781,0.6704
2016-12-06,INFY,EQ,961.65,961.80,979.50,961.65,968.55,966.50,971.03,1781055,1.729463e+14,64774,1240008,0.6962
2016-12-07,INFY,EQ,966.50,968.00,973.00,960.20,966.70,966.40,967.48,1692990,1.637934e+14,77351,1096672,0.6478
2016-12-08,INFY,EQ,966.40,970.05,986.10,970.05,985.00,984.65,983.22,2970831,2.920978e+14,83482,2385393,0.8029
2016-12-09,INFY,EQ,984.65,985.00,1008.15,981.50,986.00,989.35,995.37,4324192,4.304150e+14,121111,3195753,0.7390
2016-12-12,INFY,EQ,989.35,982.80,982.80,965.20,978.00,977.35,972.86,2672510,2.599983e+14,74619,1834356,0.6864
2016-12-13,INFY,EQ,977.35,980.50,992.85,971.10,987.50,990.20,983.95,2427141,2.388176e+14,71109,1818280,0.7491
2016-12-14,INFY,EQ,990.20,991.00,1004.95,984.10,999.00,999.75,996.89,2691307,2.682939e+14,63665,1754716,0.6520
2016-12-15,INFY,EQ,999.75,997.40,1018.95,989.00,992.40,992.35,1007.80,3983208,4.014290e+14,107209,2587459,0.6496
2016-12-16,INFY,EQ,992.35,1003.80,1009.70,997.75,1004.45,1005.15,1004.24,3218371,3.232002e+14,93462,2410099,0.7489
2016-12-19,INFY,EQ,1005.15,1006.10,1008.25,994.10,1005.00,1004.65,1000.85,2062067,2.063821e+14,52933,1578575,0.7655
2016-12-20,INFY,EQ,1004.65,1002.00,1019.00,1001.30,1013.50,1012.15,1012.54,3818249,3.866137e+14,121711,2841078,0.7441
2016-12-21,INFY,EQ,1012.15,1016.00,1022.00,998.25,1002.50,1001.55,1011.82,3671988,3.715406e+14,85526,2560729,0.6974
2016-12-22,INFY,EQ,1001.55,1002.50,1007.00,969.50,986.00,984.70,987.93,3530027,3.487410e+14,109425,2137110,0.6054
2016-12-23,INFY,EQ,984.70,984.90,1006.60,973.60,988.25,988.45,989.92,3653018,3.616212e+14,87394,2010219,0.5503
2016-12-26,INFY,EQ,988.45,988.00,994.00,975.10,983.35,982.75,983.28,1606914,1.580050e+14,47565,958338,0.5964
2016-12-27,INFY,EQ,982.75,982.75,1001.90,980.00,996.90,998.95,993.09,2456408,2.439426e+14,57508,1430604,0.5824
2016-12-28,INFY,EQ,998.95,1002.95,1009.80,995.00,999.00,998.50,1003.15,2738408,2.747040e+14,81224,1853359,0.6768
2016-12-29,INFY,EQ,998.50,1003.75,1008.00,988.15,990.00,992.35,997.88,3120062,3.113452e+14,92963,2303901,0.7384
2016-12-30,INFY,EQ,992.35,998.00,1012.00,992.75,1011.00,1010.60,1006.91,3633884,3.659012e+14,100569,2574459,0.7085

In [4]:
tcs # to view the TCS data
# it has 495 rows * 14 columns

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2015-01-01,TCS,EQ,2558.25,2567.00,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883
2015-01-02,TCS,EQ,2545.55,2551.00,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683
2015-01-05,TCS,EQ,2579.45,2581.00,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207
2015-01-06,TCS,EQ,2540.25,2529.10,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894
2015-01-07,TCS,EQ,2446.60,2470.00,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724
2015-01-08,TCS,EQ,2417.70,2442.40,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759
2015-01-09,TCS,EQ,2443.80,2455.00,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415
2015-01-12,TCS,EQ,2512.30,2517.00,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654
2015-01-13,TCS,EQ,2509.70,2520.00,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259
2015-01-14,TCS,EQ,2497.90,2516.00,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575
2015-01-15,TCS,EQ,2521.95,2533.00,2581.75,2523.25,2542.05,2539.10,2550.97,2504960,6.390076e+14,96363,1598846,0.6383
2015-01-16,TCS,EQ,2539.10,2543.70,2545.00,2484.30,2526.00,2532.15,2511.39,2646915,6.647444e+14,127847,1372200,0.5184
2015-01-19,TCS,EQ,2532.15,2536.00,2551.00,2503.00,2509.00,2511.00,2516.06,567537,1.427954e+14,38860,309156,0.5447
2015-01-20,TCS,EQ,2511.00,2520.00,2530.00,2483.25,2498.00,2500.45,2498.94,1029283,2.572121e+14,58066,733487,0.7126
2015-01-21,TCS,EQ,2500.45,2522.00,2522.00,2488.25,2518.00,2513.80,2507.75,1155240,2.897055e+14,75976,771316,0.6677
2015-01-22,TCS,EQ,2513.80,2516.50,2521.25,2495.50,2511.00,2513.55,2509.31,1056607,2.651355e+14,74837,742399,0.7026
2015-01-23,TCS,EQ,2513.55,2514.00,2532.05,2496.10,2504.10,2503.60,2507.34,1575190,3.949530e+14,94619,1205911,0.7656
2015-01-27,TCS,EQ,2503.60,2512.35,2515.00,2489.55,2504.20,2502.05,2502.26,1369368,3.426510e+14,71406,1079233,0.7881
2015-01-28,TCS,EQ,2502.05,2503.00,2544.90,2502.90,2533.40,2539.60,2529.32,1560990,3.948240e+14,101994,1142166,0.7317
2015-01-29,TCS,EQ,2539.60,2538.00,2568.70,2512.90,2560.70,2544.65,2531.88,1867196,4.727520e+14,67497,1547590,0.8288
2015-01-30,TCS,EQ,2544.65,2560.70,2575.00,2470.00,2484.00,2482.05,2494.94,2908701,7.257025e+14,119200,2355497,0.8098
2015-02-02,TCS,EQ,2482.05,2482.00,2521.45,2462.05,2516.00,2514.20,2500.60,1590901,3.978211e+14,89485,1171718,0.7365
2015-02-03,TCS,EQ,2514.20,2511.65,2565.00,2507.10,2552.25,2558.25,2536.23,1172527,2.973793e+14,75106,701449,0.5982
2015-02-04,TCS,EQ,2558.25,2568.00,2571.70,2502.10,2514.95,2514.30,2523.08,1122709,2.832687e+14,60615,807091,0.7189
2015-02-05,TCS,EQ,2514.30,2520.00,2591.70,2519.00,2553.00,2552.40,2558.13,2265084,5.794386e+14,77935,1638106,0.7232
2015-02-06,TCS,EQ,2552.40,2553.00,2594.80,2550.85,2576.10,2575.75,2578.40,1068208,2.754265e+14,82449,582019,0.5449
2015-02-09,TCS,EQ,2575.75,2561.50,2569.10,2500.00,2512.00,2512.90,2531.83,1038216,2.628585e+14,72967,695542,0.6699
2015-02-10,TCS,EQ,2512.90,2510.00,2526.25,2433.00,2445.50,2441.15,2473.88,1899527,4.699201e+14,114773,1383973,0.7286
2015-02-11,TCS,EQ,2441.15,2455.05,2487.25,2447.25,2460.00,2459.90,2468.94,1468761,3.626283e+14,115345,1143243,0.7784
2015-02-12,TCS,EQ,2459.90,2479.80,2479.80,2447.00,2469.00,2462.15,2462.56,1553990,3.826787e+14,113845,1269759,0.8171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-21,TCS,EQ,2125.10,2126.20,2140.00,2105.00,2130.00,2132.90,2128.57,896683,1.908655e+14,63995,642120,0.7161
2016-11-22,TCS,EQ,2132.90,2132.00,2177.45,2122.05,2142.00,2135.00,2147.59,659430,1.416184e+14,38866,358511,0.5437
2016-11-23,TCS,EQ,2135.00,2149.00,2162.95,2127.20,2158.50,2156.35,2150.81,637904,1.372013e+14,40612,452131,0.7088
2016-11-24,TCS,EQ,2156.35,2154.90,2207.60,2137.00,2205.00,2188.45,2185.41,1513117,3.306774e+14,47769,989064,0.6537
2016-11-25,TCS,EQ,2188.45,2212.00,2307.25,2192.20,2299.80,2300.35,2272.25,2138074,4.858238e+14,125651,1308479,0.6120
2016-11-28,TCS,EQ,2300.35,2294.00,2319.45,2251.90,2275.05,2282.60,2283.57,962148,2.197133e+14,69327,514849,0.5351
2016-11-29,TCS,EQ,2282.60,2275.00,2292.00,2252.55,2263.00,2259.85,2271.38,721148,1.638002e+14,60419,463428,0.6426
2016-11-30,TCS,EQ,2259.85,2265.00,2294.75,2242.30,2275.00,2276.05,2272.16,1722916,3.914748e+14,88801,1019099,0.5915
2016-12-01,TCS,EQ,2276.05,2277.00,2290.00,2254.05,2267.00,2263.45,2270.78,561526,1.275101e+14,48664,264640,0.4713
2016-12-02,TCS,EQ,2263.45,2258.00,2270.80,2205.20,2229.00,2221.85,2233.56,999016,2.231366e+14,70395,643301,0.6439
2016-12-05,TCS,EQ,2221.85,2229.00,2237.85,2170.00,2188.50,2186.00,2189.99,1124763,2.463216e+14,65000,713538,0.6344
2016-12-06,TCS,EQ,2186.00,2190.00,2203.95,2169.90,2170.85,2182.35,2189.54,796722,1.744452e+14,50293,570135,0.7156
2016-12-07,TCS,EQ,2182.35,2182.20,2184.45,2145.65,2157.90,2154.55,2164.31,1032853,2.235417e+14,63105,771170,0.7466
2016-12-08,TCS,EQ,2154.55,2160.50,2199.00,2160.00,2195.00,2195.75,2185.77,1619773,3.540455e+14,74988,1378152,0.8508
2016-12-09,TCS,EQ,2195.75,2205.00,2219.90,2173.30,2193.60,2195.25,2199.22,794359,1.746969e+14,53949,486502,0.6124
2016-12-12,TCS,EQ,2195.25,2194.80,2217.60,2163.00,2210.00,2208.20,2198.33,655879,1.441838e+14,43775,351270,0.5356
2016-12-13,TCS,EQ,2208.20,2218.00,2218.00,2183.00,2210.75,2200.30,2199.64,1073767,2.361901e+14,58059,661252,0.6158
2016-12-14,TCS,EQ,2200.30,2214.00,2224.70,2189.00,2208.80,2207.60,2207.22,935183,2.064159e+14,46920,678185,0.7252
2016-12-15,TCS,EQ,2207.60,2202.00,2272.10,2202.00,2256.50,2259.30,2257.49,2147705,4.848414e+14,74707,1632465,0.7601
2016-12-16,TCS,EQ,2259.30,2277.00,2290.00,2252.00,2284.80,2282.65,2275.76,993615,2.261230e+14,55542,701348,0.7059
2016-12-19,TCS,EQ,2282.65,2280.00,2297.70,2261.30,2285.00,2288.90,2274.60,667105,1.517400e+14,44317,499245,0.7484
2016-12-20,TCS,EQ,2288.90,2292.00,2345.00,2287.05,2340.00,2339.30,2322.69,1461380,3.394334e+14,49014,943670,0.6457
2016-12-21,TCS,EQ,2339.30,2343.80,2343.80,2305.60,2312.00,2313.60,2318.50,1017451,2.358959e+14,85491,774330,0.7610
2016-12-22,TCS,EQ,2313.60,2306.00,2325.00,2286.20,2315.60,2307.70,2306.01,934150,2.154160e+14,47737,585230,0.6265
2016-12-23,TCS,EQ,2307.70,2300.00,2317.75,2278.80,2285.00,2288.10,2295.23,559477,1.284127e+14,42554,331694,0.5929
2016-12-26,TCS,EQ,2288.10,2266.00,2301.60,2266.00,2296.85,2293.10,2290.60,448704,1.027802e+14,29524,213160,0.4751
2016-12-27,TCS,EQ,2293.10,2281.50,2330.00,2281.50,2322.80,2323.40,2317.79,647346,1.500411e+14,42719,358760,0.5542
2016-12-28,TCS,EQ,2323.40,2326.70,2349.90,2303.15,2305.25,2313.40,2335.86,675209,1.577194e+14,65267,420288,0.6225
2016-12-29,TCS,EQ,2313.40,2303.00,2359.90,2303.00,2355.00,2351.70,2346.25,981758,2.303445e+14,64945,575262,0.5860
2016-12-30,TCS,EQ,2351.70,2354.90,2378.60,2345.65,2366.55,2365.55,2366.64,702874,1.663448e+14,44979,456203,0.6491

In [5]:
## B) IMPORTING OCLHV DATA FOR "NIFTY IT" INDEX, DATA LEVEL- DAILY

nifty= ns.get_history(symbol= "NIFTY IT",start= date(2015,1,1),
                            end= date(2016,12,31),index= True)

In [6]:
nifty ## to view the imported data  
# it has 495 rows * 6 columns

                Open      High       Low     Close    Volume      Turnover
Date
2015-01-01  11214.80  11235.75  11166.35  11215.70   4246150  3.575100e+09
2015-01-02  11214.65  11399.10  11214.65  11372.10  10004862  9.645600e+09
2015-01-05  11369.35  11433.75  11186.95  11248.55   8858018  1.059000e+10
2015-01-06  11186.10  11186.10  10909.00  10959.90  12515739  1.364500e+10
2015-01-07  11013.20  11042.35  10889.55  10916.00  10976356  1.203440e+10
2015-01-08  11031.15  11058.15  10915.05  11018.15  12975117  1.485630e+10
2015-01-09  11058.05  11484.90  10932.20  11399.65  24812224  3.536420e+10
2015-01-12  11456.00  11565.85  11378.80  11543.65  16505074  1.712310e+10
2015-01-13  11545.25  11546.60  11437.95  11502.80  12511358  1.417510e+10
2015-01-14  11561.95  11631.55  11521.00  11614.30  12544558  1.438530e+10
2015-01-15  11672.30  11774.50  11575.10  11669.85  13882213  1.764560e+10
2015-01-16  11708.85  11708.85  11582.85  11659.60  12368107  1.714690e+10
2015-01-19  11732.50  11797.60  11629.05  11642.75  13696381  1.183750e+10
2015-01-20  11681.80  11721.90  11635.70  11695.00  11021415  1.234730e+10
2015-01-21  11732.45  11838.30  11659.70  11813.70  18679282  1.973070e+10
2015-01-22  11832.55  11884.50  11782.95  11850.85  15715515  1.655670e+10
2015-01-23  11877.90  11921.00  11767.40  11885.15  30034833  2.001210e+10
2015-01-27  11915.60  11917.25  11679.55  11693.45  17005337  1.866840e+10
2015-01-28  11712.55  11821.80  11693.80  11809.55  16876897  1.937590e+10
2015-01-29  11812.35  11861.50  11728.75  11824.15  15520902  2.160790e+10
2015-01-30  11998.35  12003.35  11799.35  11824.75  18559078  2.905950e+10
2015-02-02  11871.35  11972.60  11847.80  11943.95  17272113  2.304050e+10
2015-02-03  11963.75  12000.65  11849.00  11963.90  21053605  1.770590e+10
2015-02-04  12027.10  12027.10  11902.35  11938.90  14453955  1.290570e+10
2015-02-05  11967.75  12295.35  11963.80  12165.15  15826989  2.124010e+10
2015-02-06  12190.70  12380.45  12186.95  12267.95  11167848  1.325990e+10
2015-02-09  12160.90  12285.45  12160.90  12249.30  10996415  1.221010e+10
2015-02-10  12215.20  12297.75  12129.65  12162.85  17687306  1.851870e+10
2015-02-11  12198.45  12265.70  12149.35  12243.40  12905131  1.363700e+10
2015-02-12  12277.20  12397.00  12253.05  12372.00  16012381  1.515950e+10
...              ...       ...       ...       ...       ...           ...
2016-11-21   9500.00   9553.70   9430.40   9453.75  12187155  9.185200e+09
2016-11-22   9492.35   9566.70   9471.20   9509.45  10320661  7.296000e+09
2016-11-23   9559.10   9571.55   9484.45   9549.85  11234249  8.630900e+09
2016-11-24   9561.40   9726.50   9518.90   9656.25  18981651  1.659090e+10
2016-11-25   9709.15  10140.65   9696.65  10114.90  21789062  2.030860e+10
2016-11-28  10126.70  10171.80  10001.50  10106.20  12490536  1.063280e+10
2016-11-29  10099.65  10149.80  10043.20  10059.60   9368688  7.701600e+09
2016-11-30  10086.55  10139.95  10011.45  10087.65  14229629  1.285790e+10
2016-12-01  10090.00  10108.80  10002.40  10049.75   9518941  7.487100e+09
2016-12-02  10018.15  10061.20   9898.90   9922.75   9513403  8.425700e+09
2016-12-05   9908.30   9946.90   9778.95   9836.00   8242545  7.497000e+09
2016-12-06   9850.90   9946.75   9808.35   9834.95   7018872  6.468000e+09
2016-12-07   9865.65   9871.70   9764.20   9777.90   8046891  7.224200e+09
2016-12-08   9819.90   9947.40   9819.65   9935.90   9564747  9.456400e+09
2016-12-09   9961.95  10059.95   9925.85   9997.50  12004522  1.031460e+10
2016-12-12   9960.30   9971.25   9846.20   9953.90   8348374  8.187900e+09
2016-12-13   9983.70  10082.15   9929.85  10058.65  10363616  8.874700e+09
2016-12-14  10091.55  10150.95  10044.15  10128.95  11850616  9.295500e+09
2016-12-15  10099.05  10299.80  10091.60  10195.75  16986840  1.494020e+10
2016-12-16  10265.65  10268.70  10188.25  10222.95  10931162  9.276100e+09
2016-12-19  10213.45  10234.05  10153.80  10223.65   7460302  6.359300e+09
2016-12-20  10239.85  10352.65  10224.45  10322.85  11510080  1.100560e+10
2016-12-21  10357.30  10357.30  10207.25  10228.25   9569302  8.782600e+09
2016-12-22  10210.25  10251.20  10084.25  10163.00   9432930  8.653400e+09
2016-12-23  10162.40  10187.25  10048.85  10071.05   9770830  8.379900e+09
2016-12-26  10028.90  10065.75   9979.60  10023.30   5510950  4.446000e+09
2016-12-27   9997.00  10188.65   9994.95  10170.70   7812402  6.465800e+09
2016-12-28  10203.85  10301.10  10177.40  10198.60  10320156  8.102500e+09
2016-12-29  10194.15  10314.35  10183.40  10291.85  13889741  1.097080e+10
2016-12-30  10325.35  10416.60  10304.65  10399.25   9966961  8.624000e+09

[495 rows x 6 columns]

# The required data for all symbols have been imported

# PART 1:

In [7]:
# 1. Create 4,16,....,52 week moving average (closing price) for each stock and index. Through a defined function

## Creating a dataframe consisting of the Closing Price of all stocks/index
data= pd.DataFrame({"INFY": infy['Close'],
                  "TCS": tcs['Close'],
                   "NIFTY_IT": nifty['Close']})
data.tail(5)

               INFY      TCS  NIFTY_IT
Date
2016-12-26   982.75  2293.10  10023.30
2016-12-27   998.95  2323.40  10170.70
2016-12-28   998.50  2313.40  10198.60
2016-12-29   992.35  2351.70  10291.85
2016-12-30  1010.60  2365.55  10399.25

In [8]:
## to plot all three together
import matplotlib.pyplot as mlt
mlt.rcParams['figure.figsize']=[15,10]
data.plot(secondary_y= ["INFY","NIFTY_IT"],grid=True)

In [9]:
## creating moving averages from mean with rolling window= 10
rolling_10= np.round(data.rolling(window=10,center= False).mean(),2)
rolling_10

               INFY      TCS  NIFTY_IT
Date
2015-01-01      NaN      NaN       NaN
2015-01-02      NaN      NaN       NaN
2015-01-05      NaN      NaN       NaN
2015-01-06      NaN      NaN       NaN
2015-01-07      NaN      NaN       NaN
2015-01-08      NaN      NaN       NaN
2015-01-09      NaN      NaN       NaN
2015-01-12      NaN      NaN       NaN
2015-01-13      NaN      NaN       NaN
2015-01-14  2028.27  2501.52  11279.08
2015-01-15  2044.25  2500.88  11324.50
2015-01-16  2054.76  2496.14  11353.24
2015-01-19  2065.42  2493.22  11392.66
2015-01-20  2082.42  2498.61  11466.18
2015-01-21  2103.06  2508.22  11555.95
2015-01-22  2125.36  2515.19  11639.22
2015-01-23  2139.42  2514.32  11687.77
2015-01-27  2141.47  2513.55  11702.75
2015-01-28  2147.04  2517.72  11733.42
2015-01-29  2148.72  2520.00  11754.41
2015-01-30  2149.48  2514.29  11769.90
2015-02-02  2151.34  2512.50  11798.33
2015-02-03  2153.18  2517.22  11830.44
2015-02-04  2155.04  2518.60  11854.84
2015-02-05  2157.43  2522.46  11889.98
2015-02-06  2160.84  2528.68  11931.69
2015-02-09  2164.22  2529.62  11968.10
2015-02-10  2178.40  2523.53  12015.04
2015-02-11  2192.43  2515.56  12058.43
2015-02-12  2209.00  2507.31  12113.22
...             ...      ...       ...
2016-11-21   940.51  2169.28   9630.54
2016-11-22   934.14  2155.07   9584.49
2016-11-23   927.90  2142.39   9538.63
2016-11-24   925.10  2144.25   9535.93
2016-11-25   928.91  2158.74   9581.95
2016-11-28   934.73  2176.88   9649.11
2016-11-29   939.64  2190.74   9706.37
2016-11-30   943.10  2199.38   9751.03
2016-12-01   947.68  2212.01   9806.39
2016-12-02   952.13  2221.68   9851.02
2016-12-05   957.19  2226.99   9889.24
2016-12-06   962.42  2231.73   9921.79
2016-12-07   967.03  2231.55   9944.60
2016-12-08   972.47  2232.28   9972.56
2016-12-09   973.65  2221.77   9960.82
2016-12-12   973.41  2214.33   9945.59
2016-12-13   975.17  2208.37   9945.50
2016-12-14   977.59  2201.53   9949.63
2016-12-15   979.27  2201.11   9964.23
2016-12-16   983.33  2207.19   9994.25
2016-12-19   987.63  2217.48  10033.01
2016-12-20   992.20  2233.18  10081.80
2016-12-21   995.71  2249.08  10126.84
2016-12-22   995.72  2260.28  10149.55
2016-12-23   995.63  2269.56  10156.90
2016-12-26   996.17  2278.05  10163.84
2016-12-27   997.04  2290.36  10175.05
2016-12-28   996.92  2300.95  10182.01
2016-12-29   996.92  2310.19  10191.62
2016-12-30   997.46  2318.48  10209.25

[495 rows x 3 columns]

In [10]:
## Creating moving averages from mean with rolling window= 75
rolling_75= np.round(data.rolling(window=75, center= False).mean(),2)
rolling_75

               INFY      TCS  NIFTY_IT
Date
2015-01-01      NaN      NaN       NaN
2015-01-02      NaN      NaN       NaN
2015-01-05      NaN      NaN       NaN
2015-01-06      NaN      NaN       NaN
2015-01-07      NaN      NaN       NaN
2015-01-08      NaN      NaN       NaN
2015-01-09      NaN      NaN       NaN
2015-01-12      NaN      NaN       NaN
2015-01-13      NaN      NaN       NaN
2015-01-14      NaN      NaN       NaN
2015-01-15      NaN      NaN       NaN
2015-01-16      NaN      NaN       NaN
2015-01-19      NaN      NaN       NaN
2015-01-20      NaN      NaN       NaN
2015-01-21      NaN      NaN       NaN
2015-01-22      NaN      NaN       NaN
2015-01-23      NaN      NaN       NaN
2015-01-27      NaN      NaN       NaN
2015-01-28      NaN      NaN       NaN
2015-01-29      NaN      NaN       NaN
2015-01-30      NaN      NaN       NaN
2015-02-02      NaN      NaN       NaN
2015-02-03      NaN      NaN       NaN
2015-02-04      NaN      NaN       NaN
2015-02-05      NaN      NaN       NaN
2015-02-06      NaN      NaN       NaN
2015-02-09      NaN      NaN       NaN
2015-02-10      NaN      NaN       NaN
2015-02-11      NaN      NaN       NaN
2015-02-12      NaN      NaN       NaN
...             ...      ...       ...
2016-11-21  1025.33  2430.45  10380.24
2016-11-22  1023.05  2422.81  10358.52
2016-11-23  1020.87  2415.57  10336.79
2016-11-24  1018.80  2409.34  10316.46
2016-11-25  1017.55  2404.65  10302.68
2016-11-28  1016.37  2399.76  10288.93
2016-11-29  1014.96  2394.56  10273.76
2016-11-30  1013.52  2389.58  10258.96
2016-12-01  1012.09  2384.08  10243.94
2016-12-02  1010.59  2377.58  10226.62
2016-12-05  1009.24  2370.21  10208.79
2016-12-06  1008.11  2363.42  10193.34
2016-12-07  1007.21  2357.15  10179.59
2016-12-08  1006.70  2351.25  10168.29
2016-12-09  1006.27  2345.80  10158.56
2016-12-12  1005.76  2341.26  10150.03
2016-12-13  1005.10  2335.92  10140.59
2016-12-14  1004.34  2331.06  10131.82
2016-12-15  1003.75  2327.17  10125.56
2016-12-16  1003.55  2323.94  10121.56
2016-12-19  1003.31  2321.12  10119.40
2016-12-20  1002.93  2318.39  10116.07
2016-12-21  1002.47  2315.75  10111.84
2016-12-22  1001.77  2313.09  10106.90
2016-12-23  1001.19  2310.07  10100.80
2016-12-26  1000.36  2307.52  10093.84
2016-12-27   999.62  2305.96  10089.45
2016-12-28   999.10  2305.84  10088.89
2016-12-29   998.53  2305.83  10088.89
2016-12-30   997.95  2305.92  10089.22

[495 rows x 3 columns]

# PART-2 :- DATA VISUALIZATION

In [13]:
import bokeh as bk
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show, output_file

In [27]:
## PART -3 

df= pd.DataFrame(data["INFY"])
df= df.fillna(0)
df.index= pd.to_datetime(df.index)
df.index.name= 'Date'
df.sort_index(inplace=True)
source = ColumnDataSource(df)
p= figure(x_axis_type="datetime", plot_width=500, plot_height=350)
p.line('Date','INFY',source= source)
output_file("ts.html")
show(p)